# Generated by Django 5.1.1 on 2025-06-07 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("championship_app", "0001_initial"),
        ("club_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("coach", models.CharField(blank=True, max_length=255, null=True)),
                ("captain", models.CharField(blank=True, max_length=255, null=True)),
                ("top_scorer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "top_scorer_goals",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("top_assist", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "top_assist_goals",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "top_goalkeeper",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "top_goalkeeper_clean_sheets",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="championship_app.championship",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="club_app.club",
                    ),
                ),
                (
                    "runner_up",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runner_ups",
                        to="club_app.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Title",
                "verbose_name_plural": "Titles",
                "ordering": ["-year"],
                "unique_together": {("club", "championship", "year")},
            },
        ),
    ]
