# Generated by Django 5.1.1 on 2025-06-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship_app", "0002_championship_slug"),
        ("club_app", "0001_initial"),
        ("title_app", "0002_historychampionship_quantitytitle_delete_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quantitytitle",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="quantitytitle",
            name="championship",
        ),
        migrations.RemoveField(
            model_name="quantitytitle",
            name="club",
        ),
        migrations.AlterModelOptions(
            name="historychampionship",
            options={
                "ordering": ["-year"],
                "verbose_name": "History Championship",
                "verbose_name_plural": "History Championships",
            },
        ),
        migrations.AddIndex(
            model_name="historychampionship",
            index=models.Index(
                fields=["championship"], name="title_app_h_champio_687f70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historychampionship",
            index=models.Index(fields=["club"], name="title_app_h_club_id_0ecfb4_idx"),
        ),
        migrations.AddIndex(
            model_name="historychampionship",
            index=models.Index(
                fields=["championship", "club"], name="title_app_h_champio_6d3c51_idx"
            ),
        ),
        migrations.DeleteModel(
            name="QuantityTitle",
        ),
    ]
