# Generated by Django 5.1.1 on 2025-06-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("title_app", "0003_alter_quantitytitle_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historychampionship",
            name="table_image",
            field=models.ImageField(blank=True, null=True, upload_to="history/tables/"),
        ),
    ]
