# Generated by Django 5.1.1 on 2025-06-07 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("club_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uniform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "home_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="clubs/uniforms/home/"
                    ),
                ),
                (
                    "away_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="clubs/uniforms/away/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniforms",
                        to="club_app.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uniform",
                "verbose_name_plural": "Uniforms",
            },
        ),
    ]
