# Generated by Django 5.1.1 on 2025-01-06 18:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("club_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kit_home",
                    models.ImageField(blank=True, null=True, upload_to="kits/home/"),
                ),
                ("kit_home_url", models.URLField(blank=True, null=True)),
                (
                    "kit_away",
                    models.ImageField(blank=True, null=True, upload_to="kits/away/"),
                ),
                ("kit_away_url", models.URLField(blank=True, null=True)),
                (
                    "kit_goalkeeper_home",
                    models.ImageField(blank=True, null=True, upload_to="kits/home/"),
                ),
                ("kit_goalkeeper_home_url", models.URLField(blank=True, null=True)),
                (
                    "kit_goalkeeper_away",
                    models.ImageField(blank=True, null=True, upload_to="kits/away/"),
                ),
                ("kit_goalkeeper_away_url", models.URLField(blank=True, null=True)),
                (
                    "kit_version",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("kit_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kits",
                        to="club_app.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kit",
                "verbose_name_plural": "Kits",
            },
        ),
    ]
