# Generated by Django 5.1.1 on 2025-01-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kit_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kit",
            name="kit_type",
            field=models.CharField(
                choices=[
                    ("fts", "FTS"),
                    ("fl", "FL"),
                    ("dls", "DLS"),
                    ("other", "Other"),
                ],
                default="fts",
                max_length=255,
            ),
        ),
    ]
