# Generated by Django 5.1.1 on 2025-01-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="emblem_url",
        ),
        migrations.AddField(
            model_name="club",
            name="emblem_versions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
