# Generated by Django 5.1.1 on 2025-01-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_app", "0002_remove_club_emblem_url_club_emblem_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="federation",
            field=models.CharField(
                choices=[("FCH", "FCH"), ("FCR", "FCR"), ("FCM", "FCM")],
                default="FCH",
                max_length=10,
            ),
        ),
    ]
