# Generated by Django 5.1.1 on 2025-06-07 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Championship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="championships/logos/"
                    ),
                ),
                (
                    "table_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="championships/tables/"
                    ),
                ),
                (
                    "championship_type",
                    models.CharField(
                        choices=[
                            ("LEAGUE", "League"),
                            ("KNOCKOUT", "Knockout"),
                            ("GROUP_KNOCKOUT", "Group Stage + Knockout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tier", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Championship",
                "verbose_name_plural": "Championships",
            },
        ),
    ]
