# Generated by Django 5.1.1 on 2025-06-14 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="championship",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
