# Generated by Django 5.1.1 on 2025-01-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="championship",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="championship",
            name="logo_versions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
