# Generated by Django 5.1.1 on 2025-06-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("championship_app", "0002_championship_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="championship",
            name="table_image",
        ),
    ]
