# Generated by Django 5.1.1 on 2025-06-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("championship_app", "0003_remove_championship_table_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="championship",
            name="reputation",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="championship",
            name="championship_type",
            field=models.CharField(
                choices=[
                    ("LEAGUE", "League"),
                    ("KNOCKOUT", "Knockout"),
                    ("GROUP_KNOCKOUT", "Group Stage + Knockout"),
                    ("LEAGUE_KNOCKOUT", "League + Knockout"),
                ],
                max_length=20,
            ),
        ),
    ]
